version: 2.1
workflows:
  macos:
    jobs:
      - build_for_mac
  windows:
    jobs:
      - build_for_windows:
          context: code-sign-generic
orbs:
  windows: circleci/windows@2.2.0
jobs:
  build_for_mac:
    macos:
      xcode: "11.3.1"
    steps:
      - checkout
      - run:
          name: make dist
          command: make --directory=macOS dist
      - store_artifacts:
          path: macOS/dist/scratch-link-*.pkg
      - store_artifacts:
          path: macOS/dist/mas-scratch-link-*.pkg
  build_for_windows:
    executor: windows/default
    steps:
      - checkout
      - restore_cache:
          keys:
            - nuget-cache-{{ checksum "Windows/scratch-link/packages.config" }}-{{ checksum "Windows/ScratchLinkSetup/packages.config" }}
      - run:
          name: Install dependencies using NuGet
          command: nuget restore Windows/
      - save_cache:
          paths:
            - Windows/packages/
          key: nuget-cache-{{ checksum "Windows/scratch-link/packages.config" }}-{{ checksum "Windows/ScratchLinkSetup/packages.config" }}
      - when:
          condition:
            or:
              - equal: [ master, << pipeline.git.branch >> ]
              - equal: [ develop, << pipeline.git.branch >> ]
          steps:
            - run:
              name: Import code-signing certificate
              command: ./Windows/Import-WIN_CSC.ps1
      - run:
          name: Build using MSBuild
          command: msbuild Windows/scratch-link.sln -m -p:Configuration=Release -p:Platform="Any CPU"
      - run:
          name: Move build products to artifacts directory
          command: |
            New-Item -Path Windows/ -Name Artifacts -ItemType directory
            Move-Item -Path Windows/ScratchLinkAPPX/AppPackages/ScratchLinkAPPX_*_AnyCPU_bundle.appxupload -Destination Windows/Artifacts/
            Move-Item -Path Windows/ScratchLinkSetup/bin/Release/ScratchLinkSetup-*.zip -Destination Windows/Artifacts/
      - store_artifacts:
          path: Windows/Artifacts/
